### ISSUE TITLE
[BUG]: UNCAUGHT EXCEPTION: file name must start with ".env"

### ISSUE THREAD

**Issue by georgzoeller** [dmno-dev/dmno#124]
### dmno version

0.0.21

### Steps to reproduce

bun ```dmno run test.mjs``` where test.mjs is simply ```console.log(DMNO_CONFIG)

### What is expected?

showing the DMNO_CONFIG object

### What is actually happening?

UNCAUGHT EXCEPTION: file name must start with ".env"
UNCAUGHT EXCEPTION: Error: file name must start with ".env"
    at loadDotEnvFile (file:///D:/_dev/astro-playground/astro-nomy/node_modules/dmno/src/lib/dotenv-utils.ts:78:7)
    at file:///D:/_dev/astro-playground/astro-nomy/node_modules/dmno/src/lib/dotenv-utils.ts:138:3
    at file:///D:/_dev/astro-playground/astro-nomy/node_modules/modern-async/src/asyncWrap.mjs:26:12
    at file:///D:/_dev/astro-playground/astro-nomy/node_modules/modern-async/src/asyncGeneratorMap.mjs:113:57
    at reflectAsyncStatus (file:///D:/_dev/astro-playground/astro-nomy/node_modules/modern-async/src/reflectAsyncStatus.mjs:47:23)
    at file:///D:/_dev/astro-playground/astro-nomy/node_modules/modern-async/src/asyncGeneratorMap.mjs:113:32
    at Object.asyncFct (file:///D:/_dev/astro-playground/astro-nomy/node_modules/modern-async/src/asyncWrap.mjs:26:12)
    at file:///D:/_dev/astro-playground/astro-nomy/node_modules/modern-async/src/Queue.mjs:185:14
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)

### System Info

```shell
win32, bun 1.1.24, astro latest
It migrated .env from ./ to ./dmno successfully but failed to install the integration (had to do it manually)
```

**Comment by theoephraim** [comment]
Closing for now - I think we tracked these issues down to windows support? For now we'll just recommend using WSL2.

Please reopen if you encounter similar with WSL2.
