### ISSUE TITLE
[Nit]: dmno-workspace.yaml name is redundant 

### ISSUE THREAD

**Issue by rawkode** [dmno-dev/dmno#130]
### dmno version

0.0.23

### Steps to reproduce

As this lives in the .dmno directory, could this just be workspace.yaml?

### What is expected?

Nicer file name

### What is actually happening?

Less nicer file name

**Comment by theoephraim** [comment]
The config file is now `.dmno/workspace.yaml`. Thanks for the suggestion!
It will now start to include other config related to the workpace and dmno itself - things that we want to load before attempting to parse the root `config.mts` file, which could potentially fail...
