### ISSUE TITLE
[Feature Request] 1Password Env Alternative

### ISSUE THREAD

**Issue by rawkode** [dmno-dev/dmno#131]
### Description

Currently, you recommend an "Env blob" to get around the limitations of the 1Password SDK.

This is pretty performant, but in practice is a little tedious to work with.

It involves putting together a new 1Password item that acts as an aggregate and also means duplicating a lot of secrets within 1Password too.

I'd like 1Password to make their SDK more flexible, but until then ..

### Proposed Solution

When resolving the configs, it should be possible to collect all the 1Password references and provide a "template" that 1Password can interpolate via the inject command.

### Additional Information

This does have some limitations:

- Can only work with 1Password CLI
- Would only work with secret references
- Potentially require the use of tmpfs to keep secrets secure on disk

**Comment by theoephraim** [comment]
Yeah totally - the env blob is nice for folks coming from using a `.env` file. If you already have things split up, it definitely makes more sense to map them individually. At that point though, why not just use `itemByReference` (or `itemById`/`itemByLink`) for each item - your dmno config file is then acting as that template to map those 1pass items back into your config.

The only downside I can think of are the multiple requests. Everything is heavily cached though, and we have been chatting with the 1pass folks about supporting bulk fetch capabilities. We could even internally try to do some tricks with inject as you suggest but at least hide it from you.

**Comment by rawkode** [comment]
The multiple requests was my idea for this, as with 20 items it can be rather slow.

However, the preference is definitely for 1Password to support fetching multiple items.

Happy to close this off and hope they do that at some point.

**Comment by theoephraim** [comment]
gotcha. I'll see if I can do something hacky with inject as you suggested, but make it transparent to the end user
