### ISSUE TITLE
[BUG]: yarn compatibility gotchas

### ISSUE THREAD

**Issue by theoephraim** [dmno-dev/dmno#145]
### dmno version

latest

### Steps to reproduce

report of yarn 2 not working as expected, but need to dig in deeper

### What is expected?

it should work normally

### What is actually happening?

not working :(

### Any additional comments?

this is likely because of assumptions around `node_modules` folder and yarn having it's own ideas about how to do things...

**Comment by Inlustra** [comment]
Tad disappointed in doing a yarn dlx init myself. 
I was under the impression that - according to the docs - each monorepo package would be getting its own .dmno directory.

```
....
? Can we move out/workspaces/scheduling-ops/.env? yes
✨ moved out/workspaces/scheduling-ops/.env to .dmno folder
   📂 /Internal/repo/.dmno/.env
? Can we move workspaces/comms-platform/.env.dev? yes
✨ moved workspaces/comms-platform/.env.dev to .dmno folder
   📂 /Internal/repo/.dmno/.env.dev
? Can we move workspaces/comms-platform/.env.prod? yes
✨ moved workspaces/comms-platform/.env.prod to .dmno folder
....
```

My fault, I should have realised this looking at this line: `   📂 /Internal/repo/.dmno/.env.dev`
Anywho, I have a long road ahead of me re-setting up all of the .env files.
The reason I bring this up here, is because I figured I'd get started on the .dmnos for the individual repositories, but running it I'm getting: 

```
❯ yarn dlx dmno init

➤ YN0000: ┌ Resolution step
➤ YN0032: │ fsevents@npm:2.3.3: Implicit dependencies on node-gyp are discouraged
➤ YN0000: └ Completed in 3s 293ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0068: │ @graphql-codegen/cli ➤ dependencies ➤ ts-node: No matching package in the dependency tree; you may not need this rule anymore.
➤ YN0068: │ @graphql-tools/code-file-loader ➤ dependencies ➤ ts-node: No matching package in the dependency tree; you may not need this rule anymore.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0007: │ core-js-pure@npm:3.39.0 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.21.5 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 3s 101ms
➤ YN0000: Done with warnings in 6s 534ms

┌─╮╭─┬─╮╭─┬┐╭─╮ ┌─╮╭─┐┌┬┐ ╭───────────╮ 
│╷││╷│╷││╷│││╷│ ││││ ┤│││ │ ● ● │ ●   │ 
│╵│││╵││││╵││╵│ ││││ ┤│╵│ │ ● ● │   ● │ 
└─╯└┴─┴┘└┴─╯╰─╯○└─╯╰─┘╰─╯ ╰───────────╯ 
▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂

- Package manager: yarn
- Workspace root path: /Internal/repo
- Monorepo mode: ENABLED (0 child packages)

UNCAUGHT EXCEPTION: unable to detect which package you are in... whats happening?
UNCAUGHT EXCEPTION: Error: unable to detect which package you are in... whats happening?
    at DmnoCommand.<anonymous> (file:///tmp/xfs-8d21e654/dlx-28290/node_modules/dmno/src/cli/commands/init.command.ts:69:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at DmnoCommand.parseAsync (/tmp/xfs-8d21e654/dlx-28290/node_modules/dmno/node_modules/commander/lib/command.js:1092:5)
    at file:///tmp/xfs-8d21e654/dlx-28290/node_modules/dmno/src/cli/cli-executable.ts:57:3
```

`yarn 3.5.0`
`node v18.17.1`

**Comment by theoephraim** [comment]
@Inlustra - sorry for the trouble. I'll be talking a look at yarn bugs this afternoon! In theory, it should do a decent job of moving things around and scaffolding out your config files.

Feel free to hop in the discord https://chat.dmno.dev/ and can help debug as well!

**Comment by theoephraim** [comment]
Just a heads up if anyone else comes across this -
Looks like things are working correctly as long as you have a `.yarnrc.yml` file that contains `nodeLinker: node-modules`

Will be added to the docs shortly

**Comment by theoephraim** [comment]
Latest updates mean this may no longer be the case, as we are no longer looking in `node_modules` for the dmno instance to load. The remix plugin does appear to have references to node_modules, so will confirm if it is an issue.

**Comment by Inlustra** [comment]
I think this one in particular was caused by a legacy "workspaces" section in my `package.json`
I had something weird like: 
```json
"workspaces": {
    "packages" [ ... ]
}
```

Where as the workspaces should directly be an array.
Just be warned before you run the init as you may end up overwriting/losing your .env files

**Comment by theoephraim** [comment]
Thanks for the reminder. I will also add an extra check to make sure we are never overwriting .env files!
